name: open rampette
author: WeMake
markdown: kramdown
baseurl: 
permalink: blog/:year/:month/:day/:title/
plugins:
  - jekyll-sitemap
  # - jekyll-paginate
exclude: [README.md]
# paginate: 10
# paginate_path: /blog/page:num/
github: [metadata]

title: "open rampette by opencarecc"
tagline: "miglioriamo l’accessibilità degli esercizi commerciali"

# multilingual stuff
index:
  it:
  en: en/index.html

default_lang: "it"
  