name: open rampette
author: WeMake
markdown: kramdown
baseurl: 
permalink: /blog/:year/:month/:day/:title/
gems:
  - jekyll-sitemap
  - jekyll-paginate
  # - jekyll-polyglot
exclude: [README.md]
paginate: 10
paginate_path: /blog/page:num/
github: [metadata]

# jekyll polyglot stuff

# languages: ["it", "en"]
# default_lang: "it"
# exclude_from_localization: ["javascript", "images", "css"]
# parallel_localization: true
# data_dir: ./_data
# destination:  ./_site

# title:
#   en: "open rampette by opencarecc"
#   it: "open rampette by opencarecc"

title: "open rampette"
tagline: "miglioriamo l’accessibilità degli esercizi commerciali"